language: node_js
node_js:
- node
branches:
  only: "-master"
before_script:
- npm install -g firebase-tools
cache:
  directories:
  - node_modules
env:
  global:
    secure: FHwSSSXHvCrpGRLLKU2wV8lZRS+sb3biTTHbW3tG5PlbFhWhmigsbe0grCS86FWNgBRy5MtsCL5C4jL74TUK0HD/eAGf81lZCl0W9AiRZFJY82ZehhXjzqM0taWRU/saXD4/UyGom7cFdMrowof3mEXwVsiQcP+2gQYBaGecNhAyaPd5QhW+ve+9MYgfKVvEmAiUpw206i4cCCLR0S4PvNk6V6tCuJW8F7M5T8Lbaow2KAWQi6AEN3yDXuqlv3efNDIa+tJ4wr3eyFYquVPgcghFDHx7VgLhmejYqyfEvoQO++Dt02lMi1a5LomncuZBbVmM3XEiy9YejNeyaQjhVz6keMNDIcNO7UoivKa8PFYOXFwU89/iOg0movRZ4CVhyLtyqDNCp+oMFbd7yFKWKd/BDNg2rxxGBh/nzYQrLPRbkEYehVDwkl8LNekBwwsWSDJqaUZ6QL3k6srlJvu2/FIque0y6OofnjYg7F6rFN+mMOmvTHDqKF09HXUY00m8TrekQYmrQ6oappkUWi/9ALkRukPw+w7PTmRIUyILG3OuaOicjsmbbV8/8Q7yu6Nuz/D9buZHE3vtcFFxeLLNtjLEAl7+NHrj20b9DwVTJWhWBGUvfD5qS0ELCuH4W0Pk1FZUhDJqVloHpovyhTqM1/wQx0f9I5ul1jDO9HsELHg=

deploy:
  provider: firebase
  token:
    secure: "FHwSSSXHvCrpGRLLKU2wV8lZRS+sb3biTTHbW3tG5PlbFhWhmigsbe0grCS86FWNgBRy5MtsCL5C4jL74TUK0HD/eAGf81lZCl0W9AiRZFJY82ZehhXjzqM0taWRU/saXD4/UyGom7cFdMrowof3mEXwVsiQcP+2gQYBaGecNhAyaPd5QhW+ve+9MYgfKVvEmAiUpw206i4cCCLR0S4PvNk6V6tCuJW8F7M5T8Lbaow2KAWQi6AEN3yDXuqlv3efNDIa+tJ4wr3eyFYquVPgcghFDHx7VgLhmejYqyfEvoQO++Dt02lMi1a5LomncuZBbVmM3XEiy9YejNeyaQjhVz6keMNDIcNO7UoivKa8PFYOXFwU89/iOg0movRZ4CVhyLtyqDNCp+oMFbd7yFKWKd/BDNg2rxxGBh/nzYQrLPRbkEYehVDwkl8LNekBwwsWSDJqaUZ6QL3k6srlJvu2/FIque0y6OofnjYg7F6rFN+mMOmvTHDqKF09HXUY00m8TrekQYmrQ6oappkUWi/9ALkRukPw+w7PTmRIUyILG3OuaOicjsmbbV8/8Q7yu6Nuz/D9buZHE3vtcFFxeLLNtjLEAl7+NHrj20b9DwVTJWhWBGUvfD5qS0ELCuH4W0Pk1FZUhDJqVloHpovyhTqM1/wQx0f9I5ul1jDO9HsELHg="
  project: "firefly-client-2ccd2"